public class ArithmeticCalculation {
    public void Addition(integer x, integer y) {
       integer xy= x+y;
       system.debug ('the total is= '+ xy);

       
    }

    public void Subs(integer x,integer y){
        integer z= x-y;
        system.debug ('write the result = '+ z);
        }



     public void Multiplication (integer x, integer y, integer m){
        integer z = x*y*m;
        system.debug(z);


     } 
}