public  class Candidates {
    public string name;
   public string gender;
   public static string companyName;
   publis static integer countCandidates=0;
   
    System.debug('-------------start.......');
    system.debug('candidate name=>'+name+'gender is'+gender);
    System.debug('company name is'+companyName );
    System.debug('-------end-----');

    public static b=void printCompany(){
        
    }
   }

    }
